api/urls.py
from django.urls import path
from django.urls.conf import include
from .views import *

app_name = 'api'
urlpatterns = [
    path('register_user/', register_user, name='register_user'),
    path('login_user/', login_user, name='login_user'),
    path('logout_user/', logout_user, name='logout_user'),
    path('list_users/', list_users, name='list_user'),
    path('update_user/', update_user, name='update_user'),
    path('update_password/', update_password, name='update_password'),
    path('update_profile/', update_profile, name='update_profile'),
    path('follow_user/<int:user_id>', follow_user, name='follow_user'),
    path('unfollow_user/<int:user_id>', unfollow_user, name='unfollow_user'),
    path('create_profile/', create_profile, name='create_profile'),
    path('get_profile/<int:user_id>', get_profile, name='get_profile'),
    path('get_comments/<int:post_id>', get_comments, name='get_comments'),
    path('list_user_posts/<int:user_id>', list_user_posts, name='list_user_posts'),
    path('list_messages/<int:sender_id>', list_messages, name='list_messages'),
    path('add_message/', add_message, name='add_message'),
    path('discover_posts/', discover_posts, name='discover_posts'),
    path('news_feed/', news_feed, name='news_feed'),
    path('create_post/', create_post, name='create_post'),
    path('update_post/<int:id>', update_post, name='update_post'),
    path('delete_post/<int:id>', delete_post, name='delete_post'),
    path('add_comment/<int:post_id>', add_comment, name='add_comment'),
    path('add_like/<int:post_id>', add_like, name='add_like'),
    path('delete_like/<int:like_id>', delete_like, name='delete_like'),
    path('delete_comment/<int:id>', delete_comment, name='delete_comment'),
]

frontend/urls.py
from django.urls import path
from django.urls.conf import include
from .views import *

app_name = 'frontend'
urlpatterns = [
    path('', redirect_home, name='redirect_home'),
    path('home/', home, name='home'),
    path('create_post/', create_post, name='create_post'),
    path('discover/', discover, name='discover'),
    path('messages/', messages, name='messages'),
    path('notifications/', notifications, name='notifications'),
    path('my_profile/', my_profile, name='my_profile'),
    path('user_profile/<int:user_id>', user_profile, name='user_profile'),
    path('login/', login, name="login"),
    path('register/', register, name="register")
]

social_media_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('frontend.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.http import request
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect

# Create your views here.
@login_required
def redirect_home(request):
    return redirect('frontend:home')
    
@login_required
def home(request):
    return render(request, 'home.html')


@login_required
def create_post(request):
    return render(request, 'create_post.html')


@login_required
def discover(request):
    return render(request, 'discover.html')


@login_required
def messages(request):
    return render(request, 'messages.html')


@login_required
def notifications(request):
    return render(request, 'notifications.html')


@login_required
def my_profile(request):
    return render(request, 'my_profile.html')


@login_required
def user_profile(request, user_id):
    return render(request, 'user_profile.html', context={'user_id': user_id})


def login(request):
    return render(request, 'login.html')


def register(request):
    return render(request, 'register.html')

frontend/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social Media App</title>
    {% load static %}
    <style>
      body{
        background: linear-gradient(to right, #e96443, #904e95);
      }
      @media (max-width: 1100px){
      .right-col, .search-box{
          display: none;
      }
      .nav-wrapper,
      .wrapper{
          width: 90%;
      }
  
      .wrapper{
          display: block;
      }
  }
  
  @media (max-width: 500px){
      .nav-items .icon{
          margin: 0 2px;
      }
      .post-image{
          height: 300px;
      }
  }
    </style>

    <!-- CSS only -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- JavaScript Bundle with Popper -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>

<body>
  <input type="hidden" id="my_id" value="{{request.user.id}}">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <!-- <a class="navbar-brand" href="#">Welcome {{request.user.username}}</a> -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:home' %}"><img src="{% static 'bootstrap-icons/house.svg'%}" width="30px" id="home"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:messages' %}"><img src="{% static 'bootstrap-icons/chat-dots.svg'%}" width="30px" id="messages"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:create_post' %}"><img src="{% static 'bootstrap-icons/plus-circle.svg'%}" width="30px" id="create_post"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:discover' %}"><img src="{% static 'bootstrap-icons/compass.svg'%}" width="30px" id="discover"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:my_profile' %}"><img src="{% static 'bootstrap-icons/person.svg'%}" width="30px" id="profile"></a>
          </li>
        </ul>
        <div class="d-flex">
          <input class="form-control me-2" id="search-input" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-primary" id="search-btn" onclick="search_result()" data-bs-toggle="modal" data-bs-target="#exampleModal">Search</button>
        </div>
      </div>
    </div>
  </nav>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Users</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="users-modal">
          ...
        </div>
      </div>
    </div>
  </div>

  <script>
    function search_result(){
      fetch('https://prouserr.pythonanywhere.com/api/list_users').then((resp) => resp.json()).then(function(users){
        search_query = document.getElementById('search-input').value
        users_modal = document.getElementById('users-modal')
        users_modal.innerHTML = ''
        for(i in users){
          if(users[i].username.includes(search_query)){
            fetch(`https://prouserr.pythonanywhere.com/api/get_profile/${users[i].id}`).then((resp) => resp.json()).then(function(profile){
              users_modal.innerHTML += `
              <div>
                      <a href="https://prouserr.pythonanywhere.com/user_profile/${profile.id}" style="text-decoration: none;">
                      <img class="rounded-cirlce" width="30px" src="${profile.image}">
                      </a>

                      <a class="underline" href="https://prouserr.pythonanywhere.com/user_profile/${profile.id}">
                          ${profile.username}
                      </a>
              </div>
              <br>
              `
          })
          }
        }
      })
    }

  </script>
  <br>
  {% block content %}
  {% endblock content %}
</body>
</html>

frontend/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <script src="{% static 'js/create_post.js' %}"></script>
    <input type="hidden" id="password" value="{{request.user.password}}">
    <div class="bg-white" style="width: 50%;margin-left: 25%;">
        <h1 style="text-align: center;">Create new post:</h1>
        <div class="container">
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Enter caption:</label>
              <input type="email" class="form-control" id="caption_input" aria-describedby="emailHelp">
            </div>
            <div>
            <label for="formFileLg" class="form-label">Select an image:</label>
                <input class="form-control form-control-lg" id="image_input" type="file">
            </div>
            <br>
            <button type="submit" class="btn btn-primary" onclick="create_post()">Submit</button>
          </div>
          <br>
    </div>
{% endblock content %}

frontend/templates/discover.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}

    <div id="my_container" class="bg-white" style="width: 60%;margin-left: 20%;">
        <main>

            <div class="container">
        
                <div class="gallery" id="gallery">
        
                </div>
                <!-- End of gallery -->
        
        
            </div>
            <!-- End of container -->
        
        </main>
    </div>


    <link rel="stylesheet" href="{% static 'css/discover.css' %}">
    <script src="{% static 'js/discover.js' %}"></script>
{% endblock content %}

frontend/templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
        <div id="my_container" style="padding-left: 35%;display: inline-block;">
        </div>


    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="{% static 'js/home.js' %}"></script>

{% endblock content %}

frontend/templates/login.html
{% extends 'base.html' %}

{% block content%}
    {% load static %}


    <div style="width: 50%;margin-left: 25%;">
        <div class="card card0">
            <div class="d-flex flex-lg-row flex-column-reverse">
                <div class="card card1">
                    <div class="row justify-content-center my-auto">
                        <div class="col-md-8 col-10 my-5">
                            <h3 class="mb-5 text-center heading">Welcome user</h3>
                            <h6 class="msg-info">Please login to your account</h6>
                            <div class="form-group"> <label class="form-control-label text-muted">Username</label> <input type="text" id="username-input" placeholder="Username" class="form-control"> </div>
                            <div class="form-group"> <label class="form-control-label text-muted">Password</label> <input type="password" id="password-input" placeholder="Password" class="form-control"> </div>
                            <div class="row justify-content-center my-3 px-3"> <button id="login-btn" class="btn-block btn-color">Login</button> </div>
                            <div class="row justify-content-center my-2"> <a href="#"><small class="text-muted">Forgot Password?</small></a> </div>
                        </div>
                    </div>
                    <div class="bottom text-center mb-5">
                        <p href="#" class="sm-text mx-auto mb-3">Don't have an account?<a href="{% url 'frontend:register' %}" class="btn btn-white ml-2">Create new</a></p>
                    </div>
                </div>
                <div class="card card2">
                    <div class="my-auto mx-md-5 px-md-5 right">
                        <h3 class="text-white">Social Media App</h3> <small class="text-white">Connect with the world and chat with family and friends!</small>
                    </div>
                </div>
            </div>
        </div>
    </div>

      
    <script src="{% static 'js/login.js'%}"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock content %}

frontend/templates/messages.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}

    <div id="my_container"></div>

    <script src="{% static 'js/messages.js' %}"></script>
{% endblock content %}

frontend/templates/my_profile.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
  <div id="my_container" style="width: 60%;margin-left: 20%;">

  </div>

  <input type="hidden" id="password" value="{{request.user.password}}">
  
  <!-- Modal -->
  <div class="modal fade" id="SettingsModal" tabindex="-1" aria-labelledby="SettingsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
            <div class="d-grid gap-2">
                <button class="btn" type="button" onclick="display_edit_profile()">Change password</button>
                <hr>
                <button class="btn" type="button" onclick="logout()">Logout</button>
                <hr>
                <button class="btn" type="button" onclick="show_login_activity({{request.user.id}})">Login Activity</button>
            </div>
        </div>
      </div>
    </div>
  </div>
  

  <link rel="stylesheet" href="{% static 'css/my_profile.css'%}">
  <script src="{% static 'js/my_profile.js' %}"></script>
{% endblock content %}

frontend/templates/notifications.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <script src="{% static 'js/notifications.js' %}"></script>
{% endblock content %}

frontend/templates/register.html
{% extends 'base.html' %}

{% block content%}
    {% load static %}

    <div style="width: 50%;margin-left: 25%;">
        <div class="card card0">
            <div class="d-flex flex-lg-row flex-column-reverse">
                <div class="card card1">
                    <div class="row justify-content-center my-auto">
                        <div class="col-md-8 col-10 my-5">
                            <h3 class="mb-5 text-center heading">Welcome user</h3>
                            <h6 class="msg-info">Please Register to make a new account</h6>
                            <div class="form-group"> <label class="form-control-label text-muted">Username</label> <input type="text" id="username-input" placeholder="Username" class="form-control"> </div>
                            <div class="form-group"> <label class="form-control-label text-muted">Email</label> <input type="text" id="email-input" placeholder="Email" class="form-control"> </div>

                            <div class="form-group"> <label class="form-control-label text-muted">Password</label> <input type="password" placeholder="Password" id="password-input1" class="form-control"> </div>
                            <div class="form-group"> <label class="form-control-label text-muted">Type in the password again to confirm</label> <input type="password" id="password-input2" placeholder="Password" class="form-control"> </div>

                            <div class="row justify-content-center my-3 px-3"> <button id="register-btn" class="btn-block btn-color">Register</button> </div>
                        </div>
                    </div>
                </div>
                <div class="card card2">
                    <div class="my-auto mx-md-5 px-md-5 right">
                        <h3 class="text-white">Social Media App</h3> <small class="text-white">Connect with the world and chat with family and friends!</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
      
    <script src="{% static 'js/register.js'%}"></script>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock content %}

frontend/templates/user_profile.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <input type="hidden" id="user_id" value="{{user_id}}">
    <div id="my_container" style="width: 60%;margin-left: 20%;">

    </div>

    <link rel="stylesheet" href="{% static 'css/user_profile.css'%}">
    <script src="{% static 'js/user_profile.js' %}"></script>
{% endblock content %}